/*
 * This source file was generated by the Gradle 'init' task
 */
package org.teacon.ovp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OVPLibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        var classUnderTest = new OVPLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
